preset: page
fields:
  entity:
    fields:
      text: true
      files: true
  structure:
    fields:
      entity:
        fields:
          text: true
          files: true
          structure:
            fields:
              text: true