preset: page
fields:
  entity:
    label: Header
    icon: title
    toggle: true
    fields:
      text:
        width: 1/2
      logo:
        type: files
        multiple: false
        width: 1/2
      structure:
        fields:
          url: true
  structure:
    fields:
      entity:
        fields:
          text: true
          entity:
            fields:
              text: true
      structure:
        fields:
          text: true
          number: true
